package com.typhon.evolutiontool.entities;

public enum EvolutionOperator {

    ADD,
    REMOVE,
    RENAME,
    SPLITVERTICAL,
    MERGE,
    MIGRATE,
    SPLITHORIZONTAL,
    ENABLECONTAINMENT,
    DISABLECONTAINMENT,
    CHANGECONTAINMENT,
    ENABLEOPPOSITE,
    DISABLEOPPOSITE,
    CHANGECARDINALITY,
    CHANGETYPE
}
